### ISSUE TITLE
你是自学了多久？有群没？交流一下

### ISSUE THREAD

**Issue by stefansky** [yww/practice#1]
虽然干过其他开发，但也是刚开始学node，起步中

**Comment by yww** [comment]
我是做测试的，工作中写写前后端的TA。没正式做过开发，就是工作之余想自学点编程。能写点儿JS但也没有系统学过，

平时自己看看博客，翻翻书什么的。接触慕课也就是不到三个月吧，Node 也是刚接触，就跟着Scott 做了这么一个练习。

我没参加什么群，就工作之余抽时间看看慕课的视频，自己再跟着练习下。
